"""
Django settings for kaiamain project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import boto3
import os, json
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured


## (메모) BASE DIR : ./kaia_app
BASE_DIR = Path(__file__).resolve().parent.parent

# 필수: STATIC_URL
STATIC_URL = '/static/'

# collectstatic 결과물이 모일 경로 (프로젝트 밖/OneDrive 밖을 권장)
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

## (메모) 외부 접속이 허용된 호스트 
ALLOWED_HOSTS = ["*", "krcsms.com"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "eval_service.apps.EvalServiceConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kaiamain.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kaiamain.wsgi.application"

## ----------- (메모) Python Django Cache 끄기 - Cache 켜져있으면 나중에 취합시 오류 발생 가능  -----------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
## ------------------------------------------------------------------------------------------------------------------------------

## ---------- SQLite를 데이터베이스로 사용 -------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
## ---------------------------------------------------------

SECRET_KEY = os.getenv("SECRET_KEY")                          ## Django 에서 쿠키 암호화를 위하여 사용되는 비밀키
AWS_ACCESS_KEY_ID= os.getenv("AWS_ACCESS_KEY_ID")             ## AWS API 키 (공개키)
AWS_SECRET_ACCESS_KEY=os.getenv("AWS_SECRET_ACCESS_KEY")      ## AWS API 키 (개인키)
AWS_REGION=os.getenv("AWS_REGION")                            ## AWS 리전
AWS_STORAGE_BUCKET_NAME=os.getenv("AWS_STORAGE_BUCKET_NAME")  ## 접근하고자 하는 AWS S3 저장소 이름

## ------------- 회원 가입 시 인증번호 발송용 이메일 설정 -------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER  
## ------------------------------------------------------------------------------------------

## ------------ AWS S3 저장소 서비스 이용을 위한 API ---------------------------------
S3_CLIENT = boto3.client('s3',
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        region_name=AWS_REGION,
    )
## ---------------------------------------------------------------------------------